perl ../../divide.pl Feuda.JTT.2.6.phy Feuda.JTT.2.6
perl ../../divide.pl Feuda.JTT.5.2.phy Feuda.JTT.5.2
perl ../../divide.pl Feuda.JTT.7.8.phy Feuda.JTT.7.8
perl ../../divide.pl Feuda.JTT.10.4.phy Feuda.JTT.10.4
perl ../../divide.pl Feuda.JTT.13.phy Feuda.JTT.13
perl ../../divide.pl Feuda.JTT.15.6.phy Feuda.JTT.15.6
perl ../../divide.pl Feuda.JTT.18.2.phy Feuda.JTT.18.2
perl ../../divide.pl Feuda.JTT.20.8.phy Feuda.JTT.20.8
perl ../../divide.pl Feuda.JTT.23.4.phy Feuda.JTT.23.4
perl ../../divide.pl Feuda.JTT.26.phy Feuda.JTT.26
perl ../../divide.pl Feuda.JTT.28.6.phy Feuda.JTT.28.6
perl ../../divide.pl Feuda.JTT.31.2.phy Feuda.JTT.31.2
perl ../../divide.pl Feuda.JTT.33.8.phy Feuda.JTT.33.8
perl ../../divide.pl Feuda.JTT.36.4.phy Feuda.JTT.36.4
perl ../../divide.pl Feuda.JTT.39.phy Feuda.JTT.39
perl ../../divide.pl Feuda.JTT.41.6.phy Feuda.JTT.41.6
perl ../../divide.pl Feuda.JTT.44.2.phy Feuda.JTT.44.2
perl ../../divide.pl Feuda.JTT.46.8.phy Feuda.JTT.46.8
perl ../../divide.pl Feuda.JTT.49.4.phy Feuda.JTT.49.4
perl ../../divide.pl Feuda.JTT.52.phy Feuda.JTT.52
