#!/bin/sh
perl ../../divide.pl Chang.JTT.1.phy Chang.JTT.1
perl ../../divide.pl Chang.JTT.2.phy Chang.JTT.2
perl ../../divide.pl Chang.JTT.3.phy Chang.JTT.3
perl ../../divide.pl Chang.JTT.4.phy Chang.JTT.4
perl ../../divide.pl Chang.JTT.5.phy Chang.JTT.5
perl ../../divide.pl Chang.JTT.6.phy Chang.JTT.6
perl ../../divide.pl Chang.JTT.7.phy Chang.JTT.7
perl ../../divide.pl Chang.JTT.8.phy Chang.JTT.8
perl ../../divide.pl Chang.JTT.9.phy Chang.JTT.9
perl ../../divide.pl Chang.JTT.10.phy Chang.JTT.10
perl ../../divide.pl Chang.JTT.11.phy Chang.JTT.11
perl ../../divide.pl Chang.JTT.12.phy Chang.JTT.12
perl ../../divide.pl Chang.JTT.13.phy Chang.JTT.13
perl ../../divide.pl Chang.JTT.14.phy Chang.JTT.14
perl ../../divide.pl Chang.JTT.15.phy Chang.JTT.15
perl ../../divide.pl Chang.JTT.16.phy Chang.JTT.16
perl ../../divide.pl Chang.JTT.17.phy Chang.JTT.17
perl ../../divide.pl Chang.JTT.18.phy Chang.JTT.18
perl ../../divide.pl Chang.JTT.19.phy Chang.JTT.19
perl ../../divide.pl Chang.JTT.20.phy Chang.JTT.20
