#!/bin/sh
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.1.phy Chang.PAM.1
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.2.phy Chang.PAM.2
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.3.phy Chang.PAM.3
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.4.phy Chang.PAM.4
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.5.phy Chang.PAM.5
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.6.phy Chang.PAM.6
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.7.phy Chang.PAM.7
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.8.phy Chang.PAM.8
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.9.phy Chang.PAM.9
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.10.phy Chang.PAM.10
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.11.phy Chang.PAM.11
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.12.phy Chang.PAM.12
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.13.phy Chang.PAM.13
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.14.phy Chang.PAM.14
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.15.phy Chang.PAM.15
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.16.phy Chang.PAM.16
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.17.phy Chang.PAM.17
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.18.phy Chang.PAM.18
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.19.phy Chang.PAM.19
perl /Hernandez_Ryan_2019_RecodingSim/03-SATURATION/divide.pl Chang.PAM.20.phy Chang.PAM.20
