#!/bin/sh
perl ../../divide.pl Feuda.PAM.2.6.phy Feuda.PAM.2.6
perl ../../divide.pl Feuda.PAM.5.2.phy Feuda.PAM.5.2
perl ../../divide.pl Feuda.PAM.7.8.phy Feuda.PAM.7.8
perl ../../divide.pl Feuda.PAM.10.4.phy Feuda.PAM.10.4
perl ../../divide.pl Feuda.PAM.13.phy Feuda.PAM.13
perl ../../divide.pl Feuda.PAM.15.6.phy Feuda.PAM.15.6
perl ../../divide.pl Feuda.PAM.20.8.phy Feuda.PAM.20.8
perl ../../divide.pl Feuda.PAM.23.4.phy Feuda.PAM.23.4
perl ../../divide.pl Feuda.PAM.26.phy Feuda.PAM.26
perl ../../divide.pl Feuda.PAM.28.6.phy Feuda.PAM.28.6
perl ../../divide.pl Feuda.PAM.31.2.phy Feuda.PAM.31.2
perl ../../divide.pl Feuda.PAM.33.8.phy Feuda.PAM.33.8
perl ../../divide.pl Feuda.PAM.36.4.phy Feuda.PAM.36.4
perl ../../divide.pl Feuda.PAM.39.phy Feuda.PAM.39
perl ../../divide.pl Feuda.PAM.41.6.phy Feuda.PAM.41.6
perl ../../divide.pl Feuda.PAM.44.2.phy Feuda.PAM.44.2
perl ../../divide.pl Feuda.PAM.46.8.phy Feuda.PAM.46.8
perl ../../divide.pl Feuda.PAM.49.4.phy Feuda.PAM.49.4
perl ../../divide.pl Feuda.PAM.52.phy Feuda.PAM.52
